### ISSUE TITLE
Cannot find babel-polyfill

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-team#47]
When running an `mdm` command, I get `Cannot find babel-polyfill`:

```
$ mdm publish github material-motion material-motion-experiments-js
About to create a new GitHub repository.
Please confirm the details below:

    URL: https://github.com/material-motion/material-motion-experiments-js
    Command: mdm gh repo -u material-motion --new material-motion-experiments-js

Press enter to continue...
module.js:442
    throw err;
    ^

Error: Cannot find module 'babel-polyfill'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (~/Projects/material-motion-team/third_party/gh/lib/cmd.js:14:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
~/Projects/material-motion-team/contributor_tools/publish/publish: line 57: [: ==: unary operator expected
module.js:442
    throw err;
    ^

Error: Cannot find module 'babel-polyfill'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (~/Projects/material-motion-team/third_party/gh/lib/cmd.js:14:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by appsforartists** [comment]
This is because `gh` is being imported as a git submodule, so `npm install` isn't being run inside that folder.

Possible solutions:
- Install `gh` globally `npm install --global gh@version-you-care-about` and skip the submodule entirely.  So long as the team is OK being on the same version of `gh`, this seems like the best solution.
- Add a package.json to the tools root that specifies which version of `gh` you want and run `npm install` in the root folder.  Then, instead of `gh` being global, it'll be in `team/node_modules/bin/gh`.

**Comment by jverkoey** [comment]
I believe this is resolved.
